/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    MeCard: typeof import('./src/components/rm-card/me-card.vue')['default']
    MeNumberInput: typeof import('./src/components/rm-number-input/me-number-input.vue')['default']
    NumberInput: typeof import('./src/components/number-input/index.vue')['default']
    RmCard: typeof import('./src/components/rm-card/index.vue')['default']
    RmChart: typeof import('./src/components/rm-chart/index.vue')['default']
    RmEditor: typeof import('./src/components/rm-editor/index.vue')['default']
    RmFilter: typeof import('./src/components/rm-filter/index.vue')['default']
    RmInput: typeof import('./src/components/rm-input/index.vue')['default']
    RmNumberInput: typeof import('./src/components/rm-number-input/index.vue')['default']
    RmPage: typeof import('./src/components/rm-page/index.vue')['default']
    RmTable: typeof import('./src/components/rm-table/rm-table.vue')['default']
    RmUpload: typeof import('./src/components/rm-upload/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    Ui: typeof import('./src/components/ui.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
